### ISSUE TITLE
失效捏

### ISSUE THREAD

**Issue by Anstu66** [Starrylay/awesome-HUST-CS-MIPS-CPU#1]
MIPS流水CPU设计(HUST)
copy过不了实验啊

**Comment by Anstu66** [comment]
![屏幕截图 2023-05-21 141323](https://github.com/Starrylay/awesome-HUST-CS-MIPS-CPU/assets/128659304/d3015c9b-402b-40ee-be1d-6c129a3e64b0)

**Comment by Starrylay** [comment]
初衷是让你看明白，在电路里把各个功能都模块化了，也做了很多文字注释。
19级做的是MIPS听说后来改了RISC-V，另外学校的系统也会微调，直接复制想必过不了吧。
